[package]
name = 'hello'
version = '1.0.0'
authors = ['Itoh Shimon <newbee@arrow.ocn.ne.jp>']

[lib]
crate-type = ['staticlib']
path = 'hello.rs'

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
